### ISSUE TITLE
 Could not open configuration file /usr/local/apache2/conf/preset.conf: No such file or directory

### ISSUE THREAD

**Issue by richie50** [wodby/apache#7]
Below is my apache server configin the docker-compose file for 

  apache:
    image: wodby/apache:2.4-4.2.6
    container_name: "${PROJECT_NAME}_apache"
    depends_on:
      - web
    environment:
      APACHE_LOG_LEVEL: debug
      APACHE_BACKEND_HOST: web
      APACHE_VHOST_PRESET: web
      APACHE_SERVER_ROOT: /var/www/html/web 

web is my PHP docker instance. I'm basically following dupal4docker example and i run into the above error in the subject line as well as **setrlimit(RLIMIT_CORE): operation not permitted.** I don't have this issue with nginx server. Help

**Comment by csandanov** [comment]
You specified a virtual host preset to `web`, it doesn't exists by default (https://github.com/wodby/apache#virtual-hosts-presets). For custom presets you should put file `/etc/gotpl/presets/[name].conf.tmpl`

As for the setrlimit warning – you can safely ignore it, that's a bug in alpine's sudo package, it shouldn't affect anything.
