### ISSUE TITLE
Make Apache2 port dynamic (instead of hardcoded to port 80)

### ISSUE THREAD

**Issue by ck-fh** [wodby/apache#8]
Hi, it would be great if we could change the default port from '80' to something else via a Docker environment variable.

Should be possible by templating the value here:
https://github.com/wodby/apache/blob/master/templates/vhost.conf.tmpl#L1

**Comment by EvKoh** [comment]
+1000

**Comment by EvKoh** [comment]
+1000000000000000 ^^

**Comment by csandanov** [comment]
Done
